project_id = "xgvvcovmjqcpfmghawdy"

[functions.send-smtp-email]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.repair-payments]
verify_jwt = false

[functions.smtp-test]
verify_jwt = false