// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgvvcovmjqcpfmghawdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndnZjb3ZtanFjcGZtZ2hhd2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjg5MjAsImV4cCI6MjA3MTgwNDkyMH0.c6O8SlzzDjFr_87kByqsymw5liyFS6Uva-AO1mX-LAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});